theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.tabs.link
